version: "3.2"

services:
  db:
    container_name: "mysql-db"
    build: ./db/.
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - '3309:3306'

  redis:
    container_name: "redis-service"
    image: "redis:6.2"
    restart: always
    command: redis-server --loglevel warning
    ports:
      - '6375:6379'
    volumes:
      - ./cache:/data

  api:
    container_name: app-api
    restart: always
    build:
      context: ./flask-api/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./flask-api:/app
    depends_on:
      - db
      - redis

  frontend:
    container_name: app-frontend
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - api
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
